### PR TITLE
Adjusting some provisioning files to recent developments

### PR DESCRIPTION
**Pull request by heistermann**
In order to adjust to some recent changes, I had to change some of the provisioning to make sure vagrant finishes successfully. This PR addresses the following issues:

- `install_scipy_stack.sh`: the installation of IPython is broken (because
apt-get installs an outdated version of the IPython dependency "tornado") since the latest IPython requires tornado>=4.0

- `install_wradlib.sh`: some changes in wradlib dependencies which I had
to adapt to

- `install_radx.sh`: a new Radx version has become available

- `install_baltrad_bropo.sh`: Provisioning did not make sure that the ropo quality plugin has been registered to rave_pgf_quality_registry.xml

ATTENTION: There is still an unresolved issue with running the odc_toolbox on the VM. I already discussed this with Anders and Daniel and it will take some time to take care of this. However, this only affects the baltrad2wradlib interoperability demo.

### CODE REVIEW

**Comment by scollis** [comment]
Looks great Maik!

**Comment by scollis** [comment]
I'll leave you to Merge when you are happy with it.

**Comment by heistermann** [comment]
I also removed the duplicate BUFR installation as discussed in Issue #6. wradlib does not need it anymore.

**Comment by DanielMichelson** [comment]
Anders and I have been interacting with Maik about the BALTRAD-specifics of
this PR, and I'm really pleased with the way he's addressed it.

best, >-D

On Fri, Mar 27, 2015 at 10:09 AM, Maik Heistermann <notifications@github.com

**Comment by heistermann** [comment]
Please do not merge yet. There are some remaining issues regarding the order in which packages are installed. This affects the BALTRAD functionality. I am currently taking care of that.

**Comment by heistermann** [comment]
With the current changes suggested by this PR I could successfully build the VM. The problem with BALTRAD seems to be resolved - thank you Anders and Daniel for your quick help.

Please note that I included Jonathans suggestions from PR #7 for two reasons: First I got crazy because of permanent errors installing Radx, so I tried Jonathans changes to fix this. However, it turned out that the error was just an apt-get failure which simply dissolved a day later. But then I thought I keep the changes in order to avoid merging conflicts. I hope this is ok. 

As far as I am concerned, we can merge this PR.

**Comment by jjhelmus** [comment]
I had no issues creating a VM from this PR, +1 for merging.

**Pull request merged**
