### PR TITLE
Stretch

### PR DESCRIPTION
**Pull request by DanielMichelson**
Migration to Debian Stretch together with updated provisioning of BALTRAD for system Python 2 and wradlib for conda.

### CODE REVIEW

**Comment by heistermann** [comment]
The changes in `provision_scripts/install_scipy_stack.sh` imply that `jupyter` will not be installed anymore, but that the system Python environment will use the IPython `notebook` instead. 

I think that `jupyter` notebooks will not be backward compatible with IPython notebook. I expect that once a notebook will have been opened and saved in `jupyter`, it will no longer open in `notebook`.

I think at this point, the Py-ART guys (@zssherman and @scollis) need to be involved - will they continue to use the system Python environment? Are you fine with using IPython `notebook` instead of jupyter? That will probably cause problems with Py-ART notebooks once you have opened them with `jupyter` from a `conda` environment.

**If** you want to continue with `notebook`, you need to adapt `./start_notebook.sh` so it does not use `jupyter` when called from the system Python.

I would also recommend that you synchronize your `stretch` branch with `openradar/oss_weather_radar_vm/master` although there apears to be no merge conflict...

**Comment by DanielMichelson** [comment]
On Debian Stretch, installing 'python-notebook' as I have suggested
installs Jupyter:
https://packages.debian.org/search?keywords=python-notebook

The BALTRAD notebooks work, and I'm pretty sure they are a mix of ipython
and jupyter. I'm also guessing that the call to ipython-notebook is just a
wrapper to jupyter, although this would have to be verified.

**Comment by zssherman** [comment]
Taking a look now.

**Comment by zssherman** [comment]
@DanielMichelson @heistermann I like the idea of the ipython notebook change suggested above to start_notebook.sh. We can run the pyart notebooks in the openradar environment. I tried running them in system python and I can't install cartopy or the dependencies it needs. I think the change to start_notebook.sh is a good compromise.

**Comment by DanielMichelson** [comment]
I'm on it!
Spent some time this evening, but provisioning is taking unusually long, so I won't update my PR until it's done and I've verified the result.

**Comment by heistermann** [comment]
I tried your latest update - BALTRAD and wradlib notebooks work fine. Py-ART notebooks do not work yet because the sample data is not found (either not installed or wrong path/file names?) - @zssherman and @scollis once that is fixed, I am optimistic that we're up and running again. But fixing Py-ART data paths does not need to be part of this PR. So from my side, this PR can be merged.

One more thing though: For wradlib, we had an issue in a case that a notebook's metadata was still set to Python 2. If we open that notebook in the conda Python 3 environment, `jupyter` still tries to meet the notebooks preference by falling back to Python 2 in the system python environment -which of course does not contain wradlib. That issue might affect Py-ART notebooks, too. There are two ways to fix this: either fix the notebook's metadata to Python 3, or just manually switch to the Python 3 kernel in the notebook menu.

And a comment: We are in a phase of transition in which our original idea of interoperability is not working anymore. Once the BALTRAD transition to Python 3 is finalised, we should aim at making that work again, maybe we can also add BALTRAD to conda-forge...but for now, I am just happy that all packages can still run on the VM together.

**Pull request merged**
