### PR TITLE
DOC: Minor update in the docs.

### PR DESCRIPTION
**Pull request by heistermann**
Update wradlib link and wradlib dev. team.

### CODE REVIEW

**Comment by heistermann** [comment]
I already updated the html docs on openradar.git.io accordingly.

**Comment by jjhelmus** [comment]
Looks good but the history seems to be a bit messy because of the non-ff merge. Many currently merged commits are shadowed.  Can you cherry-pick b391208 into a branch based off the current GitHub master?  I can do this for you if you prefer.

**Comment by heistermann** [comment]
Yes, I agree that was messy...sorry! I am afraid I won't figure it out the way you suggested, but I can offer to just make a fresh fork from openradar/oss_weather_radar_vm, insert my minimal changes there and create a new PR...

**Comment by jjhelmus** [comment]
Another branch and PR would be fine. There may be a method to push a new set of commits to this PR, but I would not worry about it.  The workflow I would suggest is:

```
$ git remote add openradar https://github.com/openradar/oss_weather_radar_vm.git
$ git fetch openradar
$ git checkout -b doc_update upstream/master 
$ git cherry-pick b391208
$ git push origin doc_update 
```

**Comment by heistermann** [comment]
Thanks für the hint. I am stuck with the last command. It appears that `git push` tries to push to the remote master branch instead of creating a new remote brnach named `doc_update`. Here's what I get:

```
E:\src\git\heistermann\oss_weather_radar_vm [doc_update]> git push origin doc_up
date
To https://github.com/heistermann/oss_weather_radar_vm.git
 ! [rejected]        doc_update -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/heistermann/oss_weather_r
adar_vm.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

Please note I changed the 3rd command to `git checkout -b doc_update openradar/master`

Any idea?
Maik

**Comment by jjhelmus** [comment]
I believe you can specify the remote branch in the git push to override the default, `git push origin doc_update:doc_update`.  

Not sure why it is trying to push to the master branch. Might be how the tracking was set up, which can be changed using the `--set-upstream-to`, `-u` or `--set-upstream` flag of the `git branch` command depending on what version of git you are using.

**Comment by heistermann** [comment]
Thanks a lot - it worked. Closing this PR and replacing it by #19.

**Pull request closed without merging**
