### PR TITLE
Added PyTMatrix and its notebooks

### PR DESCRIPTION
**Pull request by DanielMichelson**

### CODE REVIEW

**Comment by heistermann** [comment]
I think it would be good, at least in the future, to explicitely document this as a new feature of the VM. This would at least include to add it to the features (see http://openradar.github.io/features.html) and to the courses (see http://openradar.github.io/courses.html). Otherwise, it'll be kind of hidden for potential users.

These changes would affect brief edits of

- doc/source/features.rst
- doc/source/courses.rst

**Comment by DanielMichelson** [comment]
Good point Maik. I didn't think that far. I'll try to address this asap, once I'm off the ferry from Estonia and back in the office.

Best

**Comment by DanielMichelson** [comment]
Hej again,

Sorry for the delay. I have added PyTMatrix to the features and courses as
Maik suggested.
I also tried to remove the BALTRAD-finalize provision script, but that
turned out to be a bad idea so I put it back.
Good enough to merge?

best, >-D

**Comment by heistermann** [comment]
+1 from me. Thanks, Daniel!

**Comment by jjhelmus** [comment]
Looks good to me also, merging.

**Pull request merged**
