### PR TITLE
BALTRAD: removed dependencies on jprops and keyczar

### PR DESCRIPTION
**Pull request by DanielMichelson**
Thanks to Agustín Martina.
Hope this doesn't cause any problems.
More changes coming, specifically to the pyart2baltrad R(A) notebook.

### CODE REVIEW

**Comment by scollis** [comment]
Very nice

-sent from a mobile device-

**Comment by heistermann** [comment]
As I learned from Jonathan lately (see Pull Request #20) - and I still agree: Wouldn't it be better to just delete the lines you do not need anymore? Keeps the code clean and readable. And you can still revert to previous versions anytime.

**Comment by DanielMichelson** [comment]
True.
I will delete instead of comment.
Best, >-D

**Comment by DanielMichelson** [comment]
Will be replaced by another PR.

**Comment by heistermann** [comment]
FYI: When you push to your remote fork, the PR will be automatically updated.

**Pull request closed without merging**
